export const SKIP_VERIFICATION_ACTIVITIES = [
  "lastone_place_5_bids",
  "lastone_bid_15_single_round",
  "lastone_participate_5_rounds",
  "lastone_place_30_bids_total",
  "lastone_share_bid_or_win_on_x",
  "ramen_swap_five_swap",
  "ramen_swap_stablecoin_to_push",
  "ramen_swap_fifteen_swaps",
  "ramen_swap_hold_three_chain_tokens",
  "ramen_swap_eth_sol_to_push",
  "moleswap_first_swap",
  "moleswap_add_liquidity",
  "moleswap_collect_fees",
  "moleswap_ten_swaps",
  "moleswap_multi_pool_lp",
];
