export const SKIP_VERIFICATION_ACTIVITIES = [
  "lastone_place_bid",
  "lastone_win_50pc_claim",
  "lastone_win_3_rounds_claim",
  "lastone_bid_10_single_round",
  "lastone_participate_25_rounds",
  "lastone_participate_3_rounds",
  "lastone_bet_20pc_single_round",
  "lastone_share_bid_or_win_social",
  "ramen_swap_five_swap",
  "ramen_swap_stablecoin_to_push",
  "ramen_swap_fifteen_swaps",
  "ramen_swap_hold_three_chain_tokens",
  "ramen_swap_eth_sol_to_push",
];
