
# NOTE: before merging to main - use deploy preview from main as final copy of this file - the current implementation deploy strictly to 43 to avoid using multiple branches

name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main
concurrency: preview-${{ github.ref }}
jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        if: github.event.action != 'closed'
        env:
          VITE_APP_DISCORD_CLIENT_ID: ${{ secrets.VITE_APP_DISCORD_CLIENT_ID }}
        run: |
          echo "VITE_PR_PREVIEW_BASE=pr-43" >> $GITHUB_ENV
          echo "VITE_APP_NODE_ENV=production" >> $GITHUB_ENV
          echo "VITE_APP_DEPLOY_ENV=PREVIEW" >> $GITHUB_ENV
          echo "VITE_APP_PUBLIC_URL=https://pushchain.github.io/push-chain-portal/" >> $GITHUB_ENV
          echo "VITE_APP_DISCORD_CLIENT_ID=${{ secrets.VITE_APP_DISCORD_CLIENT_ID }}" >> $GITHUB_ENV
          yarn install
          yarn build:pr:preview

      - name: Deploy preview
        if: github.event.action != 'closed'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
          destination_dir: pr-preview/pr-43
          keep_files: true
